#!/bin/sh                                                                                                                  

server=`hostname -f`
group=$1
vm_type=$2
if [ "$group" = "" ]
then
    echo usage: $0 '<group to add instance to> <vm type>'
    exit 1
fi
[ "$vm_type" = "" ] && vm_type=t1.micro

HOME=/home/ubuntu
export HOME
USER=ubuntu
export USER

puppet node_aws bootstrap \
--image ami-c1aaabb5 \
--keyname 'puppet_provisioner' \
--type $vm_type \
--region eu-west-1 \
--security-group quick-start-1 \
--login ubuntu \
--keyfile /home/ubuntu/id_rsa \
--certname puppet \
--server $server \
--node-group=$group \
--enc-server=localhost \
--enc-port=443 \
--enc-ssl \
--enc-auth-user=stefberg1@gmail.com \
--enc-auth-passwd=secret_password

