#!/bin/sh                                                                                                                  

server=`hostname -f`
puppet node_aws bootstrap \
--image ami-c1aaabb5 \
--keyname 'puppet_provisioner' \
--type 't1.micro' \
--region eu-west-1 \
--security-group quick-start-1 \
--login ubuntu \
--keyfile ~/.ssh/id_rsa \
--certname puppet \
--server $server \
--node-group=test_group \
--enc-server=localhost \
--enc-port=443 \
--enc-ssl \
--enc-auth-user=stefberg1@gmail.com \
--enc-auth-passwd=secret_password

