#!/bin/sh                                                                                                                  

server=`hostname -f`
group=$1
if [ "$group" = "" ]
then
    echo usage: $0 '<group to add instance to>'
    exit 1
fi

HOME=/home/ubuntu
export HOME
USER=ubuntu
export USER

puppet node_aws bootstrap \
--image ami-c1aaabb5 \
--keyname 'puppet_provisioner' \
--type 't1.micro' \
--region eu-west-1 \
--security-group quick-start-1 \
--login ubuntu \
--keyfile /home/ubuntu/id_rsa \
--certname puppet \
--server $server \
--node-group=$group \
--enc-server=localhost \
--enc-port=443 \
--enc-ssl \
--enc-auth-user=stefberg1@gmail.com \
--enc-auth-passwd=secret_password

