#!/bin/sh

#conf_file=puppetmaster.conf
conf_file=/etc/puppetlabs/httpd/conf.d/puppetmaster.conf 
tmp_file=/tmp/puppetmaster.conf
cp $conf_file $conf_file.orig
pem_file=`hostname -f`.pem
dir=/etc/puppetlabs/puppet/ssl
sed "s|SSLCertificateFile.*$|SSLCertificateFile  $dir/certs/$pem_file|" < $conf_file | sed "s|SSLCertificateKeyFile.*$|SSLCertificateKeyFile  $dir/private_keys/$pem_file|"  > $tmp_file
mv $tmp_file $conf_file
diff $conf_file.orig $conf_file

name=`hostname -f`
#conf_file=puppet.conf
conf_file=/etc/puppetlabs/puppet/puppet.conf
tmp_file=/tmp/puppet.conf
cp $conf_file $conf_file.orig

sed "s/certname = .*$/certname = $name/" < $conf_file | sed "s/ server = .*$/ server = $name/" | sed "s/dns_alt_names = .*$/dns_alt_names = puppet,puppet.eu-west-1.compute.amazonaws.com,`hostname`/" > $tmp_file
mv $tmp_file $conf_file

diff $conf_file.orig $conf_file 

find $(puppet master --configprint ssldir) -name "$(puppet master --configprint certname).pem" -delete

puppet master --no-daemonize --verbose

/opt/puppet/share/puppet-dashboard/config/settings.yml

ca_server: 
inventory_server: 
file_bucket_server: 


